swagger: '2.0'
info:
    title: Bookify
    version: 1.0.0
    description: Keep track of your reading habits
paths:
    /books:
        get:
            tags:
                - Books
            responses:
                '200':
                    description: Returns a list of books
                    schema:
                        type: array
                        items:
                            type: string
                    examples:
                        application/json:
                            - Decameron
                            - Romeo and Juliet
                            - It
            summary: Get all books
            description: Returns all books that are registered in API
        post:
            tags:
                - Books
            parameters:
                -
                    name: body
                    description: The book that is to be created.
                    schema:
                        $ref: '#/definitions/new-Book'
                    in: body
                    required: true
            responses:
                '201':
                    description: New Book Created Successfully
                    schema:
                        $ref: '#/definitions/new-Book'
                '400':
                    description: 'Missing some parameter, please review request data.'
                    schema:
                        $ref: '#/definitions/error'
            summary: Create a new book into the app
            description: 'Create a new book instance with its required details, for further usage.'
    '/books/{BookID}':
        get:
            tags:
                - Books
            responses:
                '200':
                    description: Returns all details of the given <Book>
            operationId: BookID
            summary: Get full details of a book
            description: Will return all details of a given <Book> based on BookID given.
        put:
            tags:
                - Books
            parameters:
                -
                    name: body
                    description: Contains new data to be changed in the specified book.
                    schema:
                        $ref: '#/definitions/new-Book'
                    in: body
                    required: true
            responses:
                '201':
                    description: Returns 201 upon successful modification of book.
                    schema:
                        $ref: '#/definitions/new-Book'
                    examples:
                        application/json:
                            -
                                Name: rqa0vl6
                                Description: a
                                ReadingTimeMin: 28
                                PageCount: 53
                                Language: ''
                                ReleaseYear: 73
                                ISBN: 44.43
                                CoverImageUrl: scyep8s
                '400':
                    description: Returns 400 when one or multiple required parameters are missing.
                    schema:
                        $ref: '#/definitions/error'
                    examples:
                        application/json:
                            -
                                error: 'cannot change info, because some parameter is missing'
                '404':
                    description: 'Returns 404 when book that is to be modified, is not found by the given BookID.'
                    schema:
                        $ref: '#/definitions/error'
                    examples:
                        application/json:
                            -
                                error: Book not found
            operationId: BookID
            summary: Modify the details of a given <Book>
            description: Edit one or more parameters of a specified <Book>
        delete:
            tags:
                - Books
            responses:
                '204':
                    description: Returns 'No Content' when removal of book is successful
                    schema:
                        $ref: '#/definitions/error'
                    examples:
                        application/json:
                            -
                                error: No Content
                '404':
                    description: 'Returns error, when book with specific ID does not exist.'
                    schema:
                        $ref: '#/definitions/error'
                    examples:
                        application/json:
                            -
                                error: Id not found
            operationId: BookID
            summary: Delete book from app
            description: Will delete book with a given Id from the app
        parameters:
            -
                name: BookID
                description: ID of the book
                in: path
                required: true
                type: string
    /users:
        get:
            tags:
                - Users
            responses:
                '200':
                    description: Returns a list of all Users.
                    schema:
                        type: array
                        items:
                            type: string
                    examples:
                        application/json:
                            -
                                UserID: FBHBEDIGNWUR
                                UserName: dfhshwsrbh112
                                IsAdmin: false
                            -
                                UserID: FBHBEDIGNWUR
                                UserName: dfhshwsrbh112
                                IsAdmin: false
                            -
                                UserID: FBHBEDIGNWUR
                                UserName: dfhshwsrbh112
                                IsAdmin: false
            summary: Returns a list of all users with limited details.
            description: |
                Returns a list of all users with limited details.
        post:
            tags:
                - Users
            parameters:
                -
                    name: body
                    schema:
                        $ref: '#/definitions/new-User'
                    in: body
                    required: true
            responses:
                '201':
                    description: 'Send 201, when all required parameters are present and new <User> created sucessfully.'
                    schema:
                        $ref: '#/definitions/new-User'
                    examples: {}
                '400':
                    description: 'Send 400, if any of the required parameters for a new <User> are not present.'
                    schema:
                        $ref: '#/definitions/error'
                    examples:
                        application/json:
                            -
                                error: e
            summary: Adds new <User> to the app
            description: Enables user signup functions and further usage.
    /events:
        get:
            tags:
                - Events
            responses:
                '200':
                    description: Returns a list of <Event> names.
                    schema:
                        type: array
                        items:
                            type: string
                    examples:
                        application/json:
                            -
                                - Reading Event
                                - Another Reading Event
                                - Extra Special Reading Event
            summary: Get all <Event>s
            description: Returns all <Event>s that are registered in API
        post:
            tags:
                - Events
            parameters:
                -
                    name: body
                    schema:
                        $ref: '#/definitions/new-Event'
                    in: body
                    required: true
            responses:
                '201':
                    schema:
                        $ref: '#/definitions/new-Event'
                    examples:
                        application/json:
                            EventName: New Event
                            EventStartDate: '2025-10-01 10:00:00'
                            EventEndDate: '2025-10-10 10:00:00'
                            EventLocation: Online
                            EventDescription: Reading event
                            EventCost: 1
                            EventMaxParticipantCount: 100
                            EventCurrentParticipantCount: 3
                            EventLanguage: English
                '400':
                    description: 'Send 400, if any of the required parameters for a new <Event> are not present.'
                    schema:
                        $ref: '#/definitions/error'
                    examples:
                        application/json:
                            -
                                error: v2c
            summary: Adds new <Event> into the app
            description: 'Create a new <Event> instance with its required details, for further usage.'
    '/events/{EventID}':
        get:
            tags:
                - Events
            parameters:
                -
                    name: EventID
                    description: ID of Event
                    in: path
                    required: true
                    type: string
            responses:
                '200':
                    description: Returns all details of the given <Event>
                    examples:
                        application/json:
                            EventID: 019b1dcf-4ef7-7157-9ab8-051daa6b142d
                            EventName: New Event
                            EventStartDate: '2025-10-01T07:00:00.000Z'
                            EventEndDate: '2025-10-10T07:00:00.000Z'
                            EventDescription: Reading event
                            EventLocation: Online
                            EventCost: 1
                            EventMaxParticipantCount: 100
                            EventCurrentParticipantCount: 3
                            EventLanguage: English
                            createdAt: '2025-12-14T17:01:24.000Z'
                            updatedAt: '2025-12-14T17:01:24.000Z'
                '400':
                    description: 'Returns Status Code 400, when an <Event> ID is missing'
                    schema:
                        $ref: '#/definitions/error'
                    examples:
                        application/json:
                            -
                                error: xv3stgj
                '404':
                    description: 'Returns Status Code 404, when <Eevent> by this ID does not exist.'
                    schema:
                        $ref: '#/definitions/error'
                    examples:
                        application/json:
                            -
                                error: ''
            operationId: EventID
            summary: Get full details of a given <Event>
            description: Will return all details of a given <Event> based on EventID given.
        put:
            tags:
                - Events
            parameters:
                -
                    name: body
                    description: Contains new data to be changed for a specific <Event>
                    schema:
                        $ref: '#/definitions/new-Event'
                    in: body
                    required: true
            responses:
                '201':
                    description: Returns 201 upon successful modification of <Event>
                    schema:
                        $ref: '#/definitions/new-Event'
                    examples:
                        application/json:
                            -
                                EventStartDate: '2018-02-10T09:30Z'
                                EventEndDate: '2018-02-10T09:30Z'
                                EventLocation: Tallinn
                                EventCost: 79
                                EventMaxParticipantCount: 55
                                EventCurrentParticipantCount: 95
                                EventLanguage: Englisj
                                EventDescription: Super Fly Event
                                EventName: Most Wanted Book
                '400':
                    schema:
                        $ref: '#/definitions/error'
                    examples:
                        application/json:
                            -
                                error: Event missing some or all parameters required
                '404':
                    description: 'Returns Status Code 404, when ID of the modified <Event> is not found.'
                    schema:
                        $ref: '#/definitions/error'
                    examples:
                        application/json:
                            -
                                error: Event with specified ID does not exist
            operationId: EventID
            summary: Modify details of a given <Event>
            description: Edit one or more parameters of a given <Event>
        delete:
            tags:
                - Events
            responses:
                '204':
                    description: Returns "No Content" when successfully removed an <Event> from app
                    schema:
                        $ref: '#/definitions/error'
                    examples:
                        application/json:
                            -
                                error: No Content
                '400':
                    description: 'Returns error, when <Event> ID was not provided.'
                    schema:
                        $ref: '#/definitions/error'
                    examples:
                        application/json:
                            -
                                error: EventID never provided
                '404':
                    description: Returns error when <Event> with specified ID does not exist.
                    schema:
                        $ref: '#/definitions/error'
                    examples:
                        application/json:
                            -
                                error: Event not found
            operationId: EventID
            summary: Delete an <Event> from app
            description: Will delete <Event> with a given Id from the app
        parameters:
            -
                name: EventID
                description: ID of an Event
                in: path
                required: true
                type: string
    '/users/{UserID}':
        get:
            tags:
                - Users
            responses:
                '200':
                    description: Returns all details of the given <User>.
            operationId: UserID
            summary: Get full details of the User.
            description: Will return details of a given <User> based on UserID given.
        put:
            tags:
                - Users
            parameters:
                -
                    name: body
                    description: Contains new data to be changed in the specified User.
                    schema:
                        $ref: '#/definitions/new-User'
                    in: body
                    required: true
            responses:
                '200':
                    description: Modified User is accepted and new data is returned.
                    schema:
                        $ref: '#/definitions/new-User'
                    examples:
                        application/json:
                            -
                                Email: ie3g@f.com
                                UserName: srys
                                DisplayName: '8'
                                FullName: rsw srgy
                                PhoneNumber: '43647648468'
                                ProfileImageUrl: wryw
                                PagesReadTotal: 7164
                                BooksReadCount: 17
                                PasswordHASH: fl6z7
                '400':
                    description: Returns 400 when one or more parameters are missing from the request.
                    schema:
                        $ref: '#/definitions/error'
                    examples:
                        application/json:
                            -
                                error: 'Can''t change User info, because some or all parameters are missing.'
                '404':
                    description: ID of the User is not found. Returns error.
                    schema:
                        $ref: '#/definitions/error'
                    examples:
                        application/json:
                            -
                                error: User with this ID was not found.
            operationId: UserID
            summary: Modify the details of a given <User>.
            description: Edit one or multiple parameters of a specified <User>.
        delete:
            tags:
                - Users
            responses:
                '204':
                    description: Returns 'No Content' when deletion of the User is successful.
                    schema:
                        $ref: '#/definitions/error'
                    examples:
                        application/json:
                            -
                                error: No content
                '400':
                    description: Returns error when the UserID is missing from the request.
                    schema:
                        $ref: '#/definitions/error'
                    examples:
                        application/json:
                            -
                                error: Please enter the ID of the user you want to delete.
                '404':
                    description: 'Returns error, when user with the given UserID does not exist.'
                    schema:
                        $ref: '#/definitions/error'
                    examples:
                        application/json:
                            -
                                error: User with this UserID is not found.
            operationId: UserID
            summary: Delete User from the app.
            description: |
                Deletes user with a given UserID from the app.
        parameters:
            -
                name: UserID
                description: ID of the User.
                in: path
                required: true
                type: string
    '/auth/{LoginEmail}':
        get:
            tags:
                - Users
                - Auth
            responses:
                '200':
                    description: 'Returns 200, when user with email address is found'
                    schema:
                        type: array
                        items:
                            type: string
                '400':
                    description: 'Return response 400, when LoginEmail is missing.'
                    schema:
                        $ref: '#/definitions/error'
                    examples:
                        application/json:
                            -
                                error: Missing LoginEmail
                '404':
                    description: Return 404 when user with this email is not found
                    schema:
                        $ref: '#/definitions/error'
                    examples:
                        application/json:
                            -
                                error: LoginEmail not found
        parameters:
            -
                name: LoginEmail
                description: Email by which the user is logged in
                in: path
                required: true
                type: string
    /sessions:
        post:
            tags:
                - Users
                - Auth
            parameters:
                -
                    name: body
                    description: Data of the User
                    schema:
                        $ref: '#/definitions/login-User'
                    in: body
                    required: true
            responses:
                '200':
                    description: Returns selected user data for site functioning
                    schema:
                        $ref: '#/definitions/loggedIn-User'
                    examples:
                        application/json:
                            -
                                UserID: ''
                                DisplayName: '24'
                                EmailAddress: oh3u0
                                IsAdmin: true
                '400':
                    description: Returns bad request when parameters are missing
                    schema:
                        $ref: '#/definitions/error'
                    examples:
                        application/json:
                            -
                                error: Missing parameter for loging in
                '401':
                    description: Returns 401 Unauthorized when incorrect data is inserted
                    schema:
                        $ref: '#/definitions/error'
                    examples:
                        application/json:
                            -
                                error: Password mismatch
                '404':
                    description: Returns 404 when User is not found
                    schema:
                        $ref: '#/definitions/error'
                    examples:
                        application/json:
                            -
                                error: User not found
            summary: Make session get cookie
            description: Inserts a session object into database and gives the user a cookie
    /sessions/me:
        get:
            tags:
                - Users
                - Auth
            responses:
                '200':
                    description: 'Returns 200, when refresh of login successful.'
                    schema:
                        $ref: '#/definitions/loggedIn-User'
                    examples:
                        application/json:
                            -
                                UserID: 8ww
                                DisplayName: ''
                                EmailAddress: ''
                                IsAdmin: true
                '401':
                    description: "Returns 401, when reauthentication of User is unsuccessful.\r\n\L\L\r\n"
                    schema:
                        $ref: '#/definitions/error'
                    examples:
                        application/json:
                            -
                                error: 'Session expired, please log in again.'
            summary: Endpoint to refresh login
    /auth/logout:
        delete:
            tags:
                - Users
                - Auth
            responses:
                '200':
                    description: |
                        Responds 200 Ok when removal of session and logout of User is successful.
                    schema:
                        type: array
                        items:
                            type: string
                    examples:
                        application/json:
                            ok: true
                '401':
                    description: 'Respond 401 when User is trying to logout, without being logged in.'
                    schema:
                        $ref: '#/definitions/error'
                    examples:
                        application/json:
                            -
                                error: User is not logged in.
                '500':
                    description: |
                        Respond 500, when attempting to delete, but uncaught error occurs.
                    schema:
                        $ref: '#/definitions/error'
                    examples:
                        application/json:
                            -
                                error: 'Server error, please hold.'
            summary: 'Remove a session, when the user requests a logout.'
            description: |
                I remoova di spagetti.
definitions:
    new-Book:
        description: Add new book to app
        required:
            - Name
            - Language
            - Description
            - PageCount
            - ReadingTimeMin
            - ReleaseYear
            - CoverImageUrl
            - ISBN
        type: object
        properties:
            Name:
                description: ''
                type: string
            Description:
                description: ''
                type: string
            ReadingTimeMin:
                description: ''
                type: integer
            PageCount:
                description: ''
                type: integer
            Language:
                description: ''
                type: string
            ReleaseYear:
                description: ''
                type: integer
            ISBN:
                format: double
                description: ''
                type: number
            CoverImageUrl:
                description: ''
                type: string
        example:
            Name: NewBookName
            Description: NewBookDescription
            ReadingTimeMin: 1
            PageCount: 1
            Language: NewBookLanguage
            ReleaseYear: 2000
            ISBN: 1111111111111
            CoverImageUrl: NewBookCoverImageUrl
    error:
        title: Root Type for error
        description: Error
        type: object
        properties:
            error:
                type: string
        example:
            error: Error message
    delete-Book:
        title: Root Type for delete-Book
        description: ''
        type: object
        properties:
            BookID:
                type: string
        example:
            BookID: 019adf28-5ff1-70ee-85b3-2ff2ec27ce17
    new-User:
        title: Root Type for new-User
        description: |-
            { 
                "Email": "example@example.com", 
                "UserName": "user1", 
                "DisplayName": "BookifyWorm007", 
                "FullName": "John Smith", 
                "PhoneNumber": "123 456 789", 
                "PasswordHASH": "Abc123", 
                "ProfileImageUrl": "https//:image.com", 
                "PagesReadTotal": 999, 
                "BooksReadCount": 222 
            }
        required: []
        type: object
        properties:
            Email:
                type: string
            UserName:
                type: string
            DisplayName:
                type: string
            FullName:
                type: string
            PhoneNumber:
                type: string
            ProfileImageUrl:
                type: string
            PagesReadTotal:
                format: int32
                type: integer
            BooksReadCount:
                format: int32
                type: integer
            PasswordHASH:
                type: string
        example:
            Email: example@example.com
            UserName: user1
            DisplayName: BookifyWorm007
            FullName: John Smith
            PhoneNumber: 123 456 789
            PasswordHASH: Abc123
            ProfileImageUrl: 'https//:image.com'
            PagesReadTotal: 999
            BooksReadCount: 222
    new-Event:
        title: Root Type for new-Event
        description: |-
            {
                "EventName": "New Event",
                "EventStartDate": "2025-10-01 10:00:00",
                "EventEndDate": "2025-10-10 10:00:00",
                "EventLocation": "Online",
                "EventDescription": "Reading event",
                "EventCost": 1,
                "EventMaxParticipantCount": 100,
                "EventCurrentParticipantCount": 3,
                "EventLanguage": "English"
            }
        type: object
        properties:
            EventStartDate:
                format: date-time
                type: string
            EventEndDate:
                format: date-time
                type: string
            EventLocation:
                type: string
            EventCost:
                format: int32
                type: integer
            EventMaxParticipantCount:
                format: int32
                type: integer
            EventCurrentParticipantCount:
                format: int32
                type: integer
            EventLanguage:
                type: string
            EventDescription:
                type: string
            EventName:
                description: ''
                type: string
        example:
            EventName: New Event
            EventStartDate: '2025-10-01 10:00:00'
            EventEndDate: '2025-10-10 10:00:00'
            EventLocation: Online
            EventDescription: Reading event
            EventCost: 1
            EventMaxParticipantCount: 100
            EventCurrentParticipantCount: 3
            EventLanguage: English
    delete-User:
        description: ''
        required: []
        type: object
        properties:
            UserID:
                description: ''
                type: string
        example:
            -
                UserID: 019b1e4f-ff99-76ee-b6fa-005fe3e30ae9
    login-User:
        title: Root Type for login-User
        description: 'Data that the User, provides Upon an attempt to login'
        type: object
        properties:
            LoginEmail:
                type: string
            LoginPassword:
                type: string
        example:
            LoginEmail: a@b.com
            LoginPassword: '12345'
    loggedIn-User:
        title: Root Type for loggedIn-User
        description: 'Data of the user, that us returned upon successful new session or reauthenticating old session'
        type: object
        properties:
            UserID:
                type: string
            DisplayName:
                type: string
            EmailAddress:
                type: string
            IsAdmin:
                type: boolean
        example:
            UserID: 019bb2b7-0463-77e5-aab0-acbbda04ee30
            DisplayName: UserAbuser
            EmailAddress: a@b.com
            IsAdmin: false